### ISSUE TITLE
双击卡片触发连接功能后使用 Esc 取消(实现快捷键)

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [leolee9086/cc-image-tag-new#129]
目前不小心双击后只能新建一个卡片连接上去再删除这个卡片![](https://camo.githubusercontent.com/9e587498ccdb49d52a041d32cd3c49c6f409d6654f772955aa66c896e7eddab2/68747470733a2f2f7261776769742e636f6d2f72696368617264636869656e2f636f6f6c712d687474702d6170692f6d61737465722f646f63732f71712d666163652f3137332e676966)

**Comment by leolee9086** [comment]
收到  最近事情杂  进度有点慢了

**Comment by Zuoqiu-Yingyi** [comment]
@leolee9086 先忙, 我们等得起 ❤

**Comment by leolee9086** [comment]
下个版本支持快捷键 
晚些再支持自定义快捷键
