### ISSUE TITLE
貌似使用 iframe 嵌入的思源界面内容无法编辑

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [leolee9086/cc-image-tag-new#170]
不知无法编辑, 是无法进行任何操作, 所有所有操作貌似都被卡片捕获了, 导致 iframe 中滚动条也无法滚动😂

**Comment by leolee9086** [comment]
![image](https://user-images.githubusercontent.com/19915077/166099925-74ae9966-4108-4f5b-8365-762b89da0c0a.png)
尝试点击那个铅笔图标  这个交互之后再想想   编辑开关可能有点隐蔽了
卡片上有一个遮罩层 是为了在非编辑模式下捕获卡片事件来操作移动和连接等  
我可能要再想想方便移动卡片和方便编辑内容哪个更加优先
