### ISSUE TITLE
缺陷：缩放后拖拽卡片的焦点问题

### ISSUE THREAD

**Issue by Dammyxy** [leolee9086/cc-image-tag-new#61]
![缩放后的拖拽焦点问题](https://user-images.githubusercontent.com/48867926/147767423-c71b5703-7dee-41d1-910d-a2046b8da29c.gif)
缩小后拖拽卡片，鼠标会快于卡片的位置，放大后拖拽卡片，卡片会快于鼠标的位置

**Comment by leolee9086** [comment]
好的 这里应该是采用的开源组件的坐标计算有问题   下个版本尝试改进

**Comment by leolee9086** [comment]
0.0.7应该已经修复了这个问题  待会试试看
